### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by ricardopieper** [tomlokhorst/language-cil#16]
Hello, first of all, I know almost nothing about cabal and haskell, so forgive me if this is not the correct thing to do.

I tried to install this package with cabal (cabal install language-cil) and it fails because there is some problem in the bool-extras-0.3.0 package.

I saw that the file language-cil.cabal has a constraint on this package. I changed that to: `bool-extras >= 0.4` and it compiles just fine. I haven't tested if it works fine, though.

**Comment by tomlokhorst** [comment]
The 0.3.0 version of bool-extras doesn't build on GHC 7.8.

I've updated the constraints in this package, the newest version on github should now build correctly.
